name="srivignesh"
age=16
school="VVMHSS"
place="salem"
location="tiruchengode"
print(name)
print(age)
print(place)
print(location)
print(type(name))
print(type(age))
print(type(place))
print(type(location))
print(type(school))