bio={"Name":"Srivignesh","Age":"25","Native":"Tiruchengode"}
print(bio)
bio.clear()
print(bio)
print(bio)
bio={"Name":"Srivignesh","Age":"25","Native":"Tiruchengode"}
a=bio.copy()
print(a)
a=bio.get("Native")
a=bio.items()
print(a)
a=bio.keys()
a=bio.setdefault("frnds","pp")
print(bio)
a=bio.values()
print(a)
a=bio.values()
bio["CRH"]="pk"
print(a)